version: "3.9"

services:
    postgres:
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
            - .data/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=Parola123@
            - POSTGRES_USER=postgres
            - POSTGRES_DB=soa_project
        networks:
            - my-network
    rabbitmq:
        image: rabbitmq:3-management
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - .data/rabbitmq/data:/var/lib/rabbitmq
            - .data/rabbitmq/log:/var/log/rabbitmq
        networks:
            - my-network
    zookeeper:
        image: confluentinc/cp-zookeeper:6.2.0
        container_name: zookeeper
        ports:
            - "22181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - my-network
    kafka:
        image: confluentinc/cp-kafka:6.2.0
        container_name: kafka
        ports:
             - "29092:29092"
             - "9092:9092"
             - "9101:9101"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_JMX_PORT: 9101
            KAFKA_JMX_HOSTNAME: localhost
        networks:
            - my-network
    shell:
        build:
            context: ./project/frontend/ng-mf
            args:
                APP_NAME: 'dashboard'
        container_name: fe-dashboard
        ports:
            - "4200:4200"
        depends_on: 
            - login
        networks:
            - my-network
    login:
        build:
            context: ./project/frontend/ng-mf
            args:
                APP_NAME: 'login'
        container_name: fe-login
        ports:
            - "4201:4201"
        networks:
            - my-network
    listener:
        image: soa-listener
        networks:
            - my-network
        ports:
            - "8081:8081"
    soa-api:
        image: soa-api
        ports:
            - "8080:8080"
        networks:
            - my-network
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .data/nginx:/etc/nginx
        networks:
            - my-network

networks:
    my-network:
        
            
